-- Generated by THEMaker 0.2.0
-- Palette: #25CED1 #FFFFFF #FCEADE #FF8A5B #EA526F
return {
  foreground = "#F8F8F2",
  background = "#101418",
  cursor_bg = "#FFFFFF",
  cursor_fg = "#101418",
  selection_bg = "#334155",
  selection_fg = "#101418",
  ansi = { "#101418", "#EA526F", "#25CED1", "#FCEADE", "#25CED1", "#FF8A5B", "#FFFFFF", "#F8F8F2" },
  brights = { "#FCEADE", "#EA526F", "#25CED1", "#FCEADE", "#25CED1", "#FF8A5B", "#FFFFFF", "#F8F8F2" },
}
